author              = "Alex Hetherington"
title               = "Footnotes for the Future"

baseURL = "http://www.footnotesforthefuture.com/"

[menu]
[[menu.main]]
name                   = "Everything"
weight                 = 1
identifier             = "everything"
url                    = "/everything/"
[[menu.main]]
name                   = "Tags"
weight                 = 2
identifier             = "bytag"
url                    = "/bytag/"
[[menu.main]]
name                   = "Links"
weight                 = 9999
identifier             = "link"
url                    = "/links/"

[params]
	highlightThumbnailSize	= "479x q100"
	highlightVideoWidth = "479"
	highlightVideoHeight = "260"