author              = "Alex Hetherington"
title               = "Footnotes for the Future"

baseURL = "http://www.footnotesforthefuture.com/"

[[menu.main]]
name                   = "Links"
weight                 = -110
identifier             = "link"
url                    = "/links/"

[params]
	highlightThumbnailSize	= "479x q100"
	highlightVideoWidth = "479"
	highlightVideoHeight = "260"